env:
  global:
    - IMG=ghdl/synth
    - DISTR=formal
    - SCRIPT=visualize.bash
    - WORKDIR=/mnt/data
    
git:
  submodules: false

#mindless copy-paste
branches:
  only:
  - gh-pages
  - /.*/

services:
  - docker
  
before_install:
- docker pull $IMG:$DISTR
  
# Here are the list of run scripts of different DUTs/testcases
script:
    # Testing the installation of the ghdl
  - docker run -t $IMG:$DISTR ghdl --version
  
    # Mount the repo to docker, and run the hello world example
  - > 
    docker run -t -v `pwd`:$WORKDIR $IMG:$DISTR
    /bin/bash -c  "chmod u+x $WORKDIR/$SCRIPT;
	cd $WORKDIR;
	$WORKDIR/$SCRIPT"
    